### ISSUE TITLE
General questions about scripts in Rails and where to put them.

### ISSUE THREAD

**Issue by andrewfritz86** [andrewfritz86/esl_app#2]
Hey guys, running into the same issue I had last night, trying to render views and the underscore template is coming back undefined because my scripts aren't loading in order.

I tried moving my scripts for rendering views and creating models directly onto the page which contains their templates. The problem is that the scripts won't load because jquery hasn't loaded yet (the javascript_include_tag is now in the footer of application.html.css.

I then moved the JS include tags back to the header, but still no luck. Any thoughts?

**Comment by andrewfritz86** [comment]
Here is an bigger explanation of what is going on here:

Previously, my template.html file (Not the greatest name) had one template script 

```
<script type="text/template" id="citation-template">

  <p>
    <%%= citation.body %>
  </p>
</script>
```

I moved my js files from application.html below the body, and everything worked great.

Now I have added a second template

```
<script type="text/template" id="the-list">
  <p>
    <%%= word.definition %>
  </P>
</script>
```

And the function that calls _.template throws an error. However, the first template still works perfectly, so I feel like I shouldn't have to move my JS files around. I can't find anything syntactically wrong in the template.

Here are my methods to render views

```
console.log("word views linked!")

function WordView(model){
  this.$el = $("<p>");
  this.model = model;
  this.id = model.id;
  debugger
}


WordView.prototype = {

  template: _.template($("#the-list")).html(),
  //error again here. looks like the template isn't loaded yet

  render: function(){
    var template = this.template({word: this.model});
    this.$el = template;
    return this
  },

  init: function(){
    this.render();
    $(".words").append(this.$el);
    return this;
  }
}
```

**Comment by ghost** [comment]
Hey Andrew
Imma look thru your code base. Is the most recent version pushed?

**Comment by ghost** [comment]
Get your `.DS_Store` files out of your repo. It looks bush-league!

**Comment by andrewfritz86** [comment]
OK. I just pushed the most recent version. You'll notice that I commented out the old init method and am using a workaround to jsut get something on the page.

**Comment by ghost** [comment]
Thanks for coming down!
