### ISSUE TITLE
When deployed, I am getting an error that blocks my api calls due to the api URL not being secure

### ISSUE THREAD

**Issue by andrewfritz86** [andrewfritz86/esl_app#3]
Hi all, here is the message I get in the JS console when trying to make an API request. This works fine in development.

```
[blocked] The page at 'https://safe-cove-5673.herokuapp.com/story_form' was loaded over HTTPS, but ran insecure content from 'http://api.wordnik.com/v4/word.json/different/definitions?limit=200&include…ncludeTags=false&api_key=64e90a58d89a8e7f3f000001fe809d0cd55d32cb45b9f117e': this content should also be loaded over HTTPS.
```

Adding an 's' to the URL doesn't seem to help.

**Comment by ghost** [comment]
Hahaha only one person can be "assigned" at any time.

**Comment by andrewfritz86** [comment]
WELL NOW THEY TELL ME.

Anyway, I think I may be screwed here, judging from google. Need to find a secure api.

**Comment by ghost** [comment]
I can't find the API call. It's not in the word controller. Where is it?

**Comment by andrewfritz86** [comment]
It is sitting in the main.js, in the onload function.

The collins dictionary api is HTTPS, I am going to try that one.

**Comment by andrewfritz86** [comment]
I guess the issues is that I am trying to bring unsecured content into an HTTPS site, thus defeating the idea of having an HTTPS site in the first place.

**Comment by andrewfritz86** [comment]
Looks like all these other APIs are going to take days to get back to me with a key, will probably have to hardcode definitions for now :(

**Comment by ghost** [comment]
No. CORS man. MAKE YOUR API REQUEST IN YOUR SERVER APP, NOT WITH AJAX. AJAX is for YOUR SERVER ONLY!
